 Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 


In [5]:
tek_boyutlu = [1,2,3,4] 

In [45]:
len(tek_boyutlu)

4

İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

2 boyut

In [14]:
iki_boyutlu =[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

In [23]:
eleman_sayisi = len(iki_boyutlu) * len(iki_boyutlu[0])
eleman_sayisi

9

In [21]:
len(iki_boyutlu)

3

In [20]:
satir_sutun = (len(iki_boyutlu), len(iki_boyutlu[0]))
satir_sutun

(3, 3)

In [25]:
iki_boyutlu[0][1]

2

In [26]:
iki_boyutlu[1]

[4, 5, 6]

In [27]:
iki_boyutlu[1][2]

6

In [29]:
dilimleme = [satir[1:2] for satir in iki_boyutlu]
dilimleme

[[2], [5], [8]]

In [30]:
[satir[0:2] for satir in iki_boyutlu]

[[1, 2], [4, 5], [7, 8]]

üç boyutlu

In [31]:
uc_boyutlu =[[[1, 2, 3],
              [4, 5, 6]],
            [[7, 8, 9],
             [10, 11, 12]
            ]]


In [32]:
len(uc_boyutlu)

2

In [35]:
ucboyut_satir_sutun = (len(uc_boyutlu), len(uc_boyutlu[0]), len(uc_boyutlu[0][0]))
ucboyut_satir_sutun

(2, 2, 3)

In [37]:
ucboyut_eleman_sayisi = len(uc_boyutlu) * len(uc_boyutlu[0]) * len(uc_boyutlu[0][0])
ucboyut_eleman_sayisi 

12

In [38]:
uc_boyutlu[0][1]

[4, 5, 6]

In [39]:
uc_boyutlu[0][0][1]

2

In [40]:
uc_boyutlu[0][1][1]

5

In [42]:
ucboyut_dilimleme = [katman[1:2] for katman in uc_boyutlu]
ucboyut_dilimleme

[[[4, 5, 6]], [[10, 11, 12]]]

In [97]:
[katman[0:2] for katman in uc_boyutlu]

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

 
 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 


In [49]:
import numpy as np

In [52]:
birboyut_np = np.array([1,2,3,4,5,6,7,8])

In [54]:
birboyut_np[1]

5

In [55]:
birboyut_np[4]

5

In [56]:
birboyut_np[0:4]

array([1, 2, 3, 4])

In [60]:
birboyut_np[1:7:2]

array([2, 4, 6])

2 boyut

In [51]:
ikiboyut_np = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12]])

In [61]:
ikiboyut_np[1, 0]

4

In [62]:
ikiboyut_np[3, 2]

12

In [63]:
ikiboyut_np[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
ikiboyut_np[0:2:2]

array([[1, 2, 3]])

3 boyut

In [50]:
ucboyut_np = np.array([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])

In [66]:
ucboyut_np[1, 0, 1]

8

In [67]:
ucboyut_np[1, 1, 1]

11

In [74]:
ucboyut_np[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
ucboyut_np[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [72]:
ucboyut_np[1:2]

array([[[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
birboyut_np.shape

(8,)

In [81]:
birboyut_np.size

8

In [82]:
ikiboyut_np.shape

(4, 3)

In [83]:
ikiboyut_np.size

12

In [84]:
ucboyut_np.shape

(2, 2, 3)

In [85]:
ucboyut_np.size

12

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [90]:
zero_arr = np.zeros((2, 3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [91]:
one_arr = np.ones((2, 3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
satır_array = np.concatenate((zero_arr, one_arr), axis=0)
satır_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
sutun_array = np.concatenate((zero_arr, one_arr), axis=1)
sutun_array

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])